language: node_js
node_js:
  - 4.1.0
  - 4.0.0
  - 0.12
  - 0.11
  - 0.10
  - iojs-v3.0.0
  - iojs-v2.0.0
  - iojs-v1.0.0
sudo: false
script:
  - npm run test-ci
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - rm -rf ./coverage
addons:
  code_climate:
    repo_token:
      secure: "cyohzKHRRi6mRxBAOwORFO8KUxDzfr6iq3Sy1wggJAmBKRWbfOVdi/O0eC6lBFm8rVx6iWyuSf2j29tEdgKjvhNt2teiLIna4M1qGv010fyFkUv6jpRQJRZ3G00T04PvkTm+sVxTPJtjlY8R2OfK/Ps8xkInOE6XyxeDdysOMwyYoljm7xR2qqyDjRwLCxmewUlM/0g9gOT/hW8Z1mXqkgX618gQPZU1R3wLUTUSnymFQ+172/Nj/5XIUhavdG9QFP1dvygqD2jwPd4pgDo43qZLzIZe/9mxwaUfVE/XE480M7Zv6N157jylMB4q1aRnoSxPbZbSefLheppYx5pwJ8K50lQNrPgTywvbGWLCJ11HhWwqDYZPHipAfDhrDy5wodNayAmqo96XsKjHgNZXY/chXutcY7bv7g7BFZRtKG3Y+qFqz97wIb7IkTWAiC5NjBQnjh30oTQt4PIMAZZvHLG6jdaLpBZN6UpzCGm6jv01A0tuiGsIGTFslAGQrOlRR1Ub9FxomaCbNUM6f1S9HGZV//NUSpKLZlD0AGDHboCdh9MEIfRsl9+Bq68FiGZ1g5hf3jSdUIrTiCmOrs4S9MUnvKdP4cQDArXZHGjxldT/TJHUoA5dCk1OqYg46/bOPGzfLwVjMo9ueYbw3db+Jh+uWPyGSEuZjYvAuUldbiE="