language: node_js
node_js:
  - 0.12
  - 0.11
  - 0.10
sudo: false
script:
  - npm run test-ci
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - rm -rf ./coverage
addons:
  code_climate:
    repo_token: 79fac9aecd202a79babfe747767556ea1d307067a3ebbf138981752180ee8ce2